### ISSUE TITLE
Run error on Mac and Windows

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/designer#207]
I got the following error every time I try to run on Windows or Mac:

    sh-3.2# gulp browser
    /Users/jkuehner/Documents/Shared/Git/github/public/designer/gulpfile.js:22
    gulp.task('symlink', () => {
                          ^
    SyntaxError: Unexpected token )
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
        at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
        at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

**Comment by justinfagnani** [comment]
Seems like you have an old version of Node. You need a version that supports ES6 Arrow Functions, like io.js 3.0, node 4.x or node 5.x.

Given that Designer is not ready to be used, I'm using any JavaScript feature that's available in a production release of Node, so if you want to try it out, I recommend using the latest version.
