### ISSUE TITLE
hydrolysis.html

### ISSUE THREAD

**Issue by dgu123** [Polymer/designer#221]
probleme with hydrolysis.html dependencies and the gulp command give the next error 
Error: stream.push() after EOF
    at readableAddChunk (C:\polymer2\designer-master\node_modules\gulp-symlink\node_modules\readable-stream\lib\_stream_readable.js:198:15)
    at DestroyableTransform.Readable.push (C:\polymer2\designer-master\node_modules\gulp-symlink\node_modules\readable-stream\lib\_stream_readable.js:176:10)
    at DestroyableTransform.Transform.push (C:\polymer2\designer-master\node_modules\gulp-symlink\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at success (C:\polymer2\designer-master\node_modules\gulp-symlink\index.js:145:22)
    at C:\polymer2\designer-master\node_modules\gulp-symlink\index.js:162:28
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by WindWen** [comment]
+1

**Comment by ajsb85** [comment]
![image](https://cloud.githubusercontent.com/assets/663460/21524769/08bb94ba-cd19-11e6-9237-0529e4c82551.png)

**Comment by leroyNicolas** [comment]
+1

**Comment by waz3** [comment]
+1

**Comment by gldan** [comment]
+1

**Comment by Toanvucp9x** [comment]
+1

**Comment by amitoj** [comment]
+1

**Comment by alexgwolff** [comment]
Windows ?  Right?
You must run with administrator privileges because symlink
Steps : 

1.  Delete files in ./vendor folder
2.  Run gulp browser or gulp electron with root

**Comment by NHKK** [comment]
@alexgwolff that still didn't work for me

+1

I'm not using gulp but npm run electron 
![image](https://user-images.githubusercontent.com/18389319/34462611-92157488-ee15-11e7-8136-2a267fa67f75.png)

**Comment by pvianca7** [comment]
+1
