### ISSUE TITLE
App is not launching - Uncaught ReferenceError: The module "uri/punycode" has not been loaded

### ISSUE THREAD

**Issue by ayapsone** [Polymer/designer#222]
how come nothing is working...very much interested in this project but could not even check out.
trying in chromium 58*

Uncaught ReferenceError: The module "uri/punycode" has not been loaded
    at _require (http://localhost:8080/components/imd/imd.js:160:13)
    at http://localhost:8080/components/imd/imd.js:117:16
    at Array.map (native)
    at _runFactory (http://localhost:8080/components/imd/imd.js:106:30)
    at define (http://localhost:8080/components/imd/imd.js:56:20)
    at http://localhost:8080/components/urijs/src/URI.js:22:5
    at http://localhost:8080/components/urijs/src/URI.js:27:2
imd.js:160 
Uncaught ReferenceError: The module "uri" has not been loaded
    at _require (http://localhost:8080/components/imd/imd.js:160:13)
    at http://localhost:8080/components/imd/imd.js:117:16
    at Array.map (native)
    at _runFactory (http://localhost:8080/components/imd/imd.js:106:30)
    at define (http://localhost:8080/components/imd/imd.js:56:20)
    at http://localhost:8080/components/polymer-designer/src/editors/ElementEditor.js:11:1
imd.js:160 
Uncaught ReferenceError: The module "polymer-designer/editors/ElementEditor" has not been loaded
    at _require (http://localhost:8080/components/imd/imd.js:160:13)
    at http://localhost:8080/components/imd/imd.js:117:16
    at Array.map (native)
    at _runFactory (http://localhost:8080/components/imd/imd.js:106:30)
    at define (http://localhost:8080/components/imd/imd.js:56:20)
    at http://localhost:8080/components/polymer-designer/elements/designer-document/designer-document.html:38:3
imd.js:160 
Uncaught ReferenceError: The module "polymer-designer/editors/ElementEditor" has not been loaded
    at _require (http://localhost:8080/components/imd/imd.js:160:13)
    at http://localhost:8080/components/imd/imd.js:117:16
    at Array.map (native)
    at _runFactory (http://localhost:8080/components/imd/imd.js:106:30)
    at define (http://localhost:8080/components/imd/imd.js:56:20)
    at http://localhost:8080/components/polymer-designer/elements/designer-element-palette/designer-element-palette.html:78:1
imd.js:160 
Uncaught ReferenceError: The module "uri" has not been loaded
    at _require (http://localhost:8080/components/imd/imd.js:160:13)
    at http://localhost:8080/components/imd/imd.js:117:16
    at Array.map (native)
    at _runFactory (http://localhost:8080/components/imd/imd.js:106:30)
    at define (http://localhost:8080/components/imd/imd.js:56:20)
    at http://localhost:8080/components/polymer-designer/elements/designer-app/designer-app.html:256:3
imd.js:160 
Uncaught ReferenceError: The module "uri" has not been loaded
    at _require (http://localhost:8080/components/imd/imd.js:160:13)
    at http://localhost:8080/components/imd/imd.js:117:16
    at Array.map (native)
    at _runFactory (http://localhost:8080/components/imd/imd.js:106:30)
    at define (http://localhost:8080/components/imd/imd.js:56:20)
    at http://localhost:8080/components/polymer-designer/elements/designer-project-service/designer-project-service-browser.html:38:3

**Comment by ayapsone** [comment]
had to fix uri.js with
 define(['punycode', 'IPv6', 'SecondLevelDomains'], factory);
instead of 
 define(['./punycode', './IPv6', './SecondLevelDomains'], factory);

it's showing some ui now..is that correct ?
drag and drop of element or infact nothing is working as per app.
